FROM arm64v8/python:3.9-buster

# Add docker entrypoint script
ADD docker-entrypoint-arm64v8.sh /
RUN chmod +x /docker-entrypoint-arm64v8.sh

# Install dependencies
RUN apt-get update \
    && apt-get install -y unzip wget

# Create directories
RUN mkdir -p /home/data/Repository/.universal \
    && mkdir -p /home/data/Repository/apps \
    && mkdir -p /home/Universal

# Add dashboard files
ADD src/Javinizer/Universal/Repository/javinizergui.ps1 /home/data/Repository/apps
ADD src/Javinizer/Universal/Repository/dashboards.ps1 /home/data/Repository/.universal

# Download PowerShell Universal 2026.1.5
WORKDIR /home
RUN wget -O /home/Universal.linux-arm64.zip https://powershelluniversal.devolutions.net/download/psu/linux-arm64/2026.1.5.0

# Extract PowerShell Universal to /home/Universal
RUN unzip -q /home/Universal.linux-arm64.zip -d /home/Universal/ \
    && chmod +x /home/Universal/Universal.Server \
    && rm /home/Universal.linux-arm64.zip

# Install mediainfo
RUN apt-get install -y mediainfo

# Install pwsh
RUN wget https://github.com/PowerShell/PowerShell/releases/download/v7.5.0/powershell-7.5.0-linux-arm64.tar.gz \
    && mkdir -p /opt/microsoft/powershell/7 \
    && tar zxf ./powershell-7.5.0-linux-arm64.tar.gz -C /opt/microsoft/powershell/7 \
    && chmod +x /opt/microsoft/powershell/7/pwsh \
    && ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# Install pwsh modules
RUN pwsh -c "Set-PSRepository 'PSGallery' -InstallationPolicy Trusted" \
    && pwsh -c "Install-Module Javinizer"

# Install python modules
RUN pip3 install pillow \
    google_trans_new \
    googletrans==4.0.0rc1 \
    requests

# Create symlink to module settings file
RUN pwsh -c "ln -s (Join-Path (Get-InstalledModule Javinizer).InstalledLocation -ChildPath jvSettings.json) /home/jvSettings.json"

# Add PowerShell Universal environment variables
ENV Kestrel__Endpoints__HTTP__Url http://*:8600
ENV Data__RepositoryPath ./data/Repository
ENV Data__ConnectionString ./data/database.db
ENV Logging__SystemLogPath ./data/logs/log.txt

EXPOSE 8600
ENTRYPOINT ["/docker-entrypoint-arm64v8.sh"]
