services:
  javinizer:
    container_name: javinizer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8600:8600
    restart: unless-stopped
    environment:
      - TZ=UTC
      - JV_SETTINGS_PATH=/home/jvSettings.json
    volumes:
      - ./data:/home/data
